### PR TITLE
Add response property to error callback

### PR DESCRIPTION
**Pull request by DenisIzmaylov**
Dear,
Thank you for your plugin. But there is real problem - we can't handle service responses in callbacks now.

For example, use case - _specified route points is not found._
In this case GraphHopper is returning a response with HTTP code 400 and some details. But in error callback ('routingerror') we could get only those info:

``` javascript
{
  status: -1,
  message: "HTTP request failed: [object XMLHttpRequest]"
}
```

I have added just one more field to this data structure which provide us possibility to handle different responses in the right way:

``` javascript
{
  status: -1,
  message: "HTTP request failed: [object XMLHttpRequest]",
  response: "{\"message\":\"Bad Request\",\"hints\":[{\"details\":\"java.lang.IllegalArgumentException\",\"message\":\"Cannot find point 0: 37.2363025,-115.8118046\"}]}"
}
```

With this fix we could handle each possible error:

``` javascript
leafletElement.on('routingerror', event => {
  const { response } = event.error;
  try {
    const parsed = JSON.parse(response);
    if (parsed['message'] == 'Bad Request' && parsed['hints']) {
      parsed['hints'].forEach(hint => {
        if (~hint['message'].indexOf('Cannot find point')) {
          self.setState({
            hasIncorrectRoutePointsError: true
          });
        }
      });
  } catch (e) {
    // nothing;
  }
});
```

### CODE REVIEW

**Comment by perliedman** [comment]
Thanks, this sounds like a nice feature.

I've added two small comments, but other than that this looks great!

**Comment by DenisIzmaylov** [comment]
Thank you for your positive feedback :) I've added a version increment as a separated commit and JSON parsing by default.

**Comment by DenisIzmaylov** [comment]
@perliedman do we need something else to get this PR finished? Or we can merge it right now?

**Comment by perliedman** [comment]
Wow, really sorry about taking almost a year to merge this. I obviously dropped this from my todo list, and unfortunately it's a bit hard to re-discover PRs and issues on GitHub.

Anyway, thanks for contributing this!

**Pull request merged**
